In [1]:
import pandas as pd

books = pd.read_csv("../data/processed/books_clean.csv")
books.head()

C:\Users\SAHRAD\AppData\Local\Temp\ipykernel_19076\1242297800.py:3: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv("../data/processed/books_clean.csv")

,Id,Name,RatingDist1,RatingDist4,RatingDistTotal,CountsOfReview,Authors,Rating,RatingDist2,RatingDist5,RatingDist3,Description,PageCount
0,1,Harry Potter and the Half-Blood Prince (Harry ...,1:9896,4:556485,total:2298124,28062,J.K. Rowling,4.57,2:25317,5:1546466,3:159960,NaN,652.0
1,2,Harry Potter and the Order of the Phoenix (Har...,1:12455,4:604283,total:2358637,29770,J.K. Rowling,4.50,2:37005,5:1493113,3:211781,NaN,870.0
2,3,Harry Potter and the Sorcerer's Stone (Harry P...,1:108202,4:1513191,total:6587388,75911,J.K. Rowling,4.47,2:130310,5:4268227,3:567458,NaN,309.0
3,4,Harry Potter and the Chamber of Secrets (Harry...,1:11896,4:706082,total:2560657,244,J.K. Rowling,4.42,2:49353,5:1504505,3:288821,NaN,352.0
4,5,Harry Potter and the Prisoner of Azkaban (Harr...,1:10128,4:630534,total:2610317,37093,J.K. Rowling,4.57,2:24849,5:1749958,3:194848,NaN,435.0

In [2]:
books["Description"] = books["Description"].fillna("")

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [4]:
tfidf = TfidfVectorizer(stop_words="english")

In [5]:
tfidf_matrix = tfidf.fit_transform(books["Description"])

In [6]:
tfidf_matrix.shape

(1847625, 963105)

In [7]:
books["Description"].notna().sum()

np.int64(1847625)

In [8]:
len(books)

1847625

In [9]:
books["Name"].duplicated().sum()

np.int64(213710)

In [10]:
books[books["Name"] == "The Hobbit"]

,Id,Name,RatingDist1,RatingDist4,RatingDistTotal,CountsOfReview,Authors,Rating,RatingDist2,RatingDist5,RatingDist3,Description,PageCount
3672,5913,The Hobbit,1:56770,4:814287,total:2747372,4,J.R.R. Tolkien,4.27,2:90969,5:1441734,3:343612,,11.0
164373,1123741,The Hobbit,1:58148,4:829331,total:2805007,125,J.R.R. Tolkien,4.27,2:92606,5:1475133,3:349789,This deluxe hardcover edition of J.R.R. Tolkie...,277.0
291499,1437245,The Hobbit,1:58411,4:831642,total:2813619,4,J.R.R. Tolkien,4.27,2:92862,5:1480016,3:350688,,290.0
527893,2075778,The Hobbit,1:59329,4:840564,total:2847644,93,J.R.R. Tolkien,4.27,2:93941,5:1499459,3:354351,The great modern classic and prelude to <i>The...,390.0
892690,205999,The Hobbit,1:57060,4:817242,total:2758877,317,J.R.R. Tolkien,4.27,2:91281,5:1448377,3:344917,,306.0
1056812,3311450,The Hobbit,1:60137,4:847671,total:2874551,7,J.R.R. Tolkien,4.27,2:94850,5:1514665,3:357228,"Dwarves, elves, goblins, trolls, dragons, and ...",5.0
1229536,349248,The Hobbit,1:57132,4:818191,total:2762521,31,J.R.R. Tolkien,4.27,2:91397,5:1450500,3:345301,,306.0
1607316,526423,The Hobbit,1:57604,4:823584,total:2783405,80,J.R.R. Tolkien,4.27,2:91984,5:1462662,3:347571,,11.0
1650374,604516,The Hobbit,1:57720,4:824891,total:2788390,119,J.R.R. Tolkien,4.27,2:92117,5:1465546,3:348116,A great modern classic and the prelude to <i>T...,291.0
1710533,714060,The Hobbit,1:57797,4:825741,total:2791475,14,J.R.R. Tolkien,4.27,2:92204,5:1467296,3:348437,"In a hole in the ground there lived a hobbit, ...",11.0
1768708,821432,The Hobbit,1:57865,4:826475,total:2794124,15,J.R.R. Tolkien,4.27,2:92265,5:1468793,3:348726,This beautifully presented collector's box of ...,295.0

In [11]:
books = books.sort_values(
    "CountsOfReview",
    ascending=False
)

In [12]:
books = books.drop_duplicates(
    subset=["Name", "Authors"],
    keep="first"
)

In [13]:
books["Name"].duplicated().sum()

np.int64(52289)

In [14]:
books[["Name", "Authors"]].duplicated().sum()

np.int64(0)

In [15]:
books.shape

(1686204, 13)

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words="english")

tfidf_matrix = tfidf.fit_transform(books["Description"])

In [17]:
tfidf_matrix.shape

(1686204, 935671)

In [18]:
books_dev = books.sample(
    n=100000,
    random_state=42
).reset_index(drop=True)

In [19]:
books_dev.shape

(100000, 13)

In [20]:
tfidf = TfidfVectorizer(stop_words="english")

tfidf_matrix = tfidf.fit_transform(
    books_dev["Description"]
)

In [21]:
tfidf_matrix.shape

(100000, 182487)

In [22]:
indices = pd.Series(
    books_dev.index,
    index=books_dev["Name"]
).drop_duplicates()

In [23]:
indices.head()

Name
Freud and Future Religious Experience                                    0
Family Fortunes: Men and Women of the English Middle Class, 1780-1850    1
Danny: El Campeon Del Mundo                                              2
Erste Bilder, Erste Wörter                                               3
Royal Treasures: A Golden Jubilee Celebration                            4
dtype: int64

In [24]:
books_dev["Name"].sample(10, random_state=42)

75721            Play It!: Over 400 Great Games for Groups
80184    Composing for Voice: A Guide for Composers, Si...
19864    The Search for Shangri-La: A Journey Into Tibe...
76699                          Famous Stories of Surprise.
92991             Elvis and the Colonel: A Christmas Carol
76434    Time and Transformation in Seventeenth-Century...
84004                                                 Toad
80917    Something Old, Something New: What You Didn't ...
60767                      The Guide to Wooden Power Boats
50074                          American Headway 1 Workbook
Name: Name, dtype: object

In [25]:
indices["Toad"]

np.int64(84004)

In [26]:
book_index = indices["Toad"]

In [27]:
book_vector = tfidf_matrix[book_index]

In [28]:
similarities = cosine_similarity(
    book_vector,
    tfidf_matrix
)

In [29]:
similarities.shape

(1, 100000)

In [30]:
similarities = similarities.flatten()

In [31]:
similarities.shape

(100000,)

In [32]:
import numpy as np

top_indices = np.argsort(similarities)[::-1]

In [ ]:
top_indices[1:11] #The first index is the book itself; the similarity rate is 100%. That's why 1:11

array([14592, 15074, 72942,  8221, 14078, 82379, 99162, 29195, 37463,
       17091])

In [36]:
books_dev.iloc[top_indices[1:11]][
    ["Name", "Authors"]
]

                                                    Name          Authors
14592                        Los Secretos de Abuelo Sapo      Keiko Kasza
15074  Dungeons & Dragons Monster Gift Set (Dungeons ...     Wizards Team
72942                             The Very Worst Monster     Pat Hutchins
8221                                  The Thumbtown Toad   George Mendoza
14078                Commander Toad and the Dis-asteroid       Jane Yolen
82379                                   Disappearing ACT   Sid Fleischman
99162  Collecting Monsters Of Film And Tv: Identifica...        Dana Cain
29195                            Frankenstein (Monsters)        Adam Woog
37463                                     Max the Dragon      Peter Stern
17091                                Wind in the Willows  Kenneth Grahame

In [39]:
books_dev["Features"] = (
    books_dev["Name"].fillna("") + " " +
    books_dev["Authors"].fillna("") + " " +
    books_dev["Description"].fillna("")
)

In [40]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

In [41]:
books_dev["Features"] = books_dev["Features"].apply(clean_text)

In [42]:
def recommend(book_name, top_n=10):
    
    if book_name not in indices:
        return "Book not found."

    idx = indices[book_name]

    similarity_scores = cosine_similarity(
        tfidf_matrix[idx],
        tfidf_matrix
    ).flatten()

    similar_indices = similarity_scores.argsort()[::-1]

    similar_indices = similar_indices[1:top_n+1]

    recommendations = books_dev.iloc[similar_indices][
        ["Name", "Authors", "Rating"]
    ].copy()

    recommendations["Similarity"] = similarity_scores[similar_indices]

    return recommendations

In [43]:
recommend("Toad")

,Name,Authors,Rating,Similarity
14592,Los Secretos de Abuelo Sapo,Keiko Kasza,3.83,0.575834
15074,Dungeons & Dragons Monster Gift Set (Dungeons ...,Wizards Team,3.82,0.340165
72942,The Very Worst Monster,Pat Hutchins,3.65,0.301399
8221,The Thumbtown Toad,George Mendoza,2.00,0.275180
14078,Commander Toad and the Dis-asteroid,Jane Yolen,3.95,0.263723
82379,Disappearing ACT,Sid Fleischman,3.46,0.252768
99162,Collecting Monsters Of Film And Tv: Identifica...,Dana Cain,3.75,0.237672
29195,Frankenstein (Monsters),Adam Woog,4.00,0.235953
37463,Max the Dragon,Peter Stern,3.75,0.224646
17091,Wind in the Willows,Kenneth Grahame,3.99,0.224213